spring.application.name=Yongnuri_Campus

# ===============================
# DATABASE CONFIGURATION
# ===============================
spring.datasource.url=jdbc:mysql://localhost:3306/ymarket?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
spring.datasource.username=root
spring.datasource.password=1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===============================
# JPA / HIBERNATE CONFIGURATION
# ===============================
# ???? DDL(create, update ?) ?? (?? ????? update ??)
spring.jpa.hibernate.ddl-auto=update
# ?? DB ??
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
# SQL ??? ??
spring.jpa.show-sql=false
# SQL ???
spring.jpa.properties.hibernate.format_sql=true


# ??? ?? // ??? ?? ?? ?? email
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=seungjin0603@gmail.com
spring.mail.password=vqpmouuoodwunglx
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# JWT ??
jwt.secret=h9PHUutbUjjDOwno01dI8GFZXa6BMakwXv0k2atQHuk=
jwt.access-token-validity=1800000
jwt.refresh-token-validity=604800000